/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//(index)'
      | '//second'
    >,
    '//(index)': RouteRecordInfo<
      '//(index)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//second': RouteRecordInfo<
      '//second',
      '/second',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/index2': RouteRecordInfo<
      '/index2',
      '/index2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools': RouteRecordInfo<
      '/tools',
      '/tools',
      Record<never, never>,
      Record<never, never>,
      | '/tools/Base64Convert'
      | '/tools/Calculator'
      | '/tools/EntryReader'
      | '/tools/IpLookup'
      | '/tools/NativeIFrame'
      | '/tools/QRCodeGen'
      | '/tools/Timestamp'
      | '/tools/UnitConvert'
      | '/tools/Weather'
      | '/tools/WoodenFish'
    >,
    '/tools/Base64Convert': RouteRecordInfo<
      '/tools/Base64Convert',
      '/tools/Base64Convert',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/Calculator': RouteRecordInfo<
      '/tools/Calculator',
      '/tools/Calculator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/EntryReader': RouteRecordInfo<
      '/tools/EntryReader',
      '/tools/EntryReader',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/IpLookup': RouteRecordInfo<
      '/tools/IpLookup',
      '/tools/IpLookup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/NativeIFrame': RouteRecordInfo<
      '/tools/NativeIFrame',
      '/tools/NativeIFrame',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/QRCodeGen': RouteRecordInfo<
      '/tools/QRCodeGen',
      '/tools/QRCodeGen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/Timestamp': RouteRecordInfo<
      '/tools/Timestamp',
      '/tools/Timestamp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/UnitConvert': RouteRecordInfo<
      '/tools/UnitConvert',
      '/tools/UnitConvert',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/Weather': RouteRecordInfo<
      '/tools/Weather',
      '/tools/Weather',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/WoodenFish': RouteRecordInfo<
      '/tools/WoodenFish',
      '/tools/WoodenFish',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//(index)'
        | '//second'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/(index).vue': {
      routes:
        | '//(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/second.vue': {
      routes:
        | '//second'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/index2.vue': {
      routes:
        | '/index2'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools.vue': {
      routes:
        | '/tools'
        | '/tools/Base64Convert'
        | '/tools/Calculator'
        | '/tools/EntryReader'
        | '/tools/IpLookup'
        | '/tools/NativeIFrame'
        | '/tools/QRCodeGen'
        | '/tools/Timestamp'
        | '/tools/UnitConvert'
        | '/tools/Weather'
        | '/tools/WoodenFish'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/tools/Base64Convert.vue': {
      routes:
        | '/tools/Base64Convert'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/Calculator.vue': {
      routes:
        | '/tools/Calculator'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/EntryReader.vue': {
      routes:
        | '/tools/EntryReader'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/IpLookup.vue': {
      routes:
        | '/tools/IpLookup'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/NativeIFrame.vue': {
      routes:
        | '/tools/NativeIFrame'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/QRCodeGen.vue': {
      routes:
        | '/tools/QRCodeGen'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/Timestamp.vue': {
      routes:
        | '/tools/Timestamp'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/UnitConvert.vue': {
      routes:
        | '/tools/UnitConvert'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/Weather.vue': {
      routes:
        | '/tools/Weather'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/WoodenFish.vue': {
      routes:
        | '/tools/WoodenFish'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
